/*
 * This file is generated by jOOQ.
*/
package model.jooq.tables.daos;


import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import model.jooq.tables.Login;
import model.jooq.tables.records.LoginRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoginDao extends DAOImpl<LoginRecord, model.pojos.Login, Long> {

    /**
     * Create a new LoginDao without any configuration
     */
    public LoginDao() {
        super(Login.LOGIN, model.pojos.Login.class);
    }

    /**
     * Create a new LoginDao with an attached configuration
     */
    public LoginDao(Configuration configuration) {
        super(Login.LOGIN, model.pojos.Login.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(model.pojos.Login object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<model.pojos.Login> fetchById(Long... values) {
        return fetch(Login.LOGIN.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public model.pojos.Login fetchOneById(Long value) {
        return fetchOne(Login.LOGIN.ID, value);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<model.pojos.Login> fetchByUsername(String... values) {
        return fetch(Login.LOGIN.USERNAME, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<model.pojos.Login> fetchByPassword(String... values) {
        return fetch(Login.LOGIN.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>password_salt IN (values)</code>
     */
    public List<model.pojos.Login> fetchByPasswordSalt(UUID... values) {
        return fetch(Login.LOGIN.PASSWORD_SALT, values);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<model.pojos.Login> fetchByActive(Boolean... values) {
        return fetch(Login.LOGIN.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<model.pojos.Login> fetchByUserId(Long... values) {
        return fetch(Login.LOGIN.USER_ID, values);
    }
}
