/*
 * This file is generated by jOOQ.
*/
package com.crmapi.model.jooq;


import com.crmapi.model.jooq.tables.User;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>crm</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USER_NAME_UINDEX = Indexes0.USER_NAME_UINDEX;
    public static final Index USER_PKEY = Indexes0.USER_PKEY;
    public static final Index USER_UUID_UINDEX = Indexes0.USER_UUID_UINDEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index USER_NAME_UINDEX = Internal.createIndex("user_name_uindex", User.USER, new OrderField[] { User.USER.NAME }, true);
        public static Index USER_PKEY = Internal.createIndex("user_pkey", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index USER_UUID_UINDEX = Internal.createIndex("user_uuid_uindex", User.USER, new OrderField[] { User.USER.UUID }, true);
    }
}
