/*
 * This file is generated by jOOQ.
*/
package com.crmapi.model.jooq;


import com.crmapi.model.jooq.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in crm
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>crm.user</code>.
     */
    public static final User USER = com.crmapi.model.jooq.tables.User.USER;
}
