/*
 * This file is generated by jOOQ.
*/
package com.crmapi.model.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 205125402;

    private Long          id;
    private UUID          uuid;
    private String        name;
    private String        surname;
    private LocalDateTime created;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.uuid = value.uuid;
        this.name = value.name;
        this.surname = value.surname;
        this.created = value.created;
    }

    public User(
        Long          id,
        UUID          uuid,
        String        name,
        String        surname,
        LocalDateTime created
    ) {
        this.id = id;
        this.uuid = uuid;
        this.name = name;
        this.surname = surname;
        this.created = created;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public UUID getUuid() {
        return this.uuid;
    }

    public void setUuid(UUID uuid) {
        this.uuid = uuid;
    }

    @NotNull
    @Size(max = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @NotNull
    @Size(max = 50)
    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public LocalDateTime getCreated() {
        return this.created;
    }

    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(uuid);
        sb.append(", ").append(name);
        sb.append(", ").append(surname);
        sb.append(", ").append(created);

        sb.append(")");
        return sb.toString();
    }
}
