/*
 * This file is generated by jOOQ.
*/
package model.pojos;


import java.io.Serializable;
import java.util.UUID;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Login implements Serializable {

    private static final long serialVersionUID = 440786111;

    private Long    id;
    private String  username;
    private String  password;
    private UUID    passwordSalt;
    private Boolean active;
    private Long    userId;

    public Login() {}

    public Login(Login value) {
        this.id = value.id;
        this.username = value.username;
        this.password = value.password;
        this.passwordSalt = value.passwordSalt;
        this.active = value.active;
        this.userId = value.userId;
    }

    public Login(
        Long    id,
        String  username,
        String  password,
        UUID    passwordSalt,
        Boolean active,
        Long    userId
    ) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.passwordSalt = passwordSalt;
        this.active = active;
        this.userId = userId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    @Size(max = 50)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @NotNull
    @Size(max = 100)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @NotNull
    public UUID getPasswordSalt() {
        return this.passwordSalt;
    }

    public void setPasswordSalt(UUID passwordSalt) {
        this.passwordSalt = passwordSalt;
    }

    public Boolean getActive() {
        return this.active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Login (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(passwordSalt);
        sb.append(", ").append(active);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
