# --- !Ups

CREATE OR REPLACE FUNCTION generate_uuid()
  RETURNS trigger AS $generate_uuid_body$
BEGIN
  IF NEW.uuid IS NULL THEN
    SELECT uuid_generate_v4() INTO NEW.uuid;;
  END IF;;
  RETURN NEW;;
END;;
$generate_uuid_body$ LANGUAGE plpgsql;;

CREATE TABLE CRM.USER
(
  ID        BIGSERIAL     PRIMARY KEY,
  UUID      UUID,
  NAME      VARCHAR(50)   NOT NULL,
  SURNAME   VARCHAR(50)   NOT NULL,
  CREATED   TIMESTAMP     DEFAULT       CURRENT_TIMESTAMP
);;

CREATE UNIQUE INDEX USER_NAME_UINDEX ON CRM.USER (NAME);;
CREATE UNIQUE INDEX USER_UUID_UINDEX ON CRM.USER (UUID);;

CREATE TRIGGER USER_UUID_TRIGGER
  BEFORE INSERT
  ON CRM.USER
  FOR EACH ROW
EXECUTE PROCEDURE generate_uuid();;


# --- !Downs

DROP TABLE CRM.USER;;
DROP FUNCTION generate_uuid();;