# --- !Ups

CREATE TABLE CRM.LOGIN
(
  ID              BIGSERIAL       PRIMARY KEY,
  USERNAME        VARCHAR(50)     NOT NULL,
  PASSWORD        VARCHAR(100)    NOT NULL,
  PASSWORD_SALT   UUID            NOT NULL,
  ACTIVE          BOOLEAN         NOT NULL      DEFAULT TRUE,
  USER_ID         BIGSERIAL       REFERENCES    CRM.USER(id),
  CREATED         TIMESTAMP,
  MODIFIED        TIMESTAMP
);;

CREATE UNIQUE INDEX LOGIN_USERNAME_UINDEX ON CRM.LOGIN (USERNAME);;

CREATE TRIGGER USER_CREATED_TRIGGER
  BEFORE INSERT
  ON CRM.LOGIN
  FOR EACH ROW
EXECUTE PROCEDURE update_created_timestamp();;

CREATE TRIGGER USER_MODIFIED_TRIGGER
  BEFORE INSERT OR UPDATE
  ON CRM.LOGIN
  FOR EACH ROW
EXECUTE PROCEDURE update_modified_timestamp();;

# --- !Downs

DROP TABLE CRM.LOGIN;;