# --- !Ups

CREATE TABLE CRM.CUSTOMER
(
  ID                    BIGSERIAL     PRIMARY KEY,
  UUID                  UUID,
  NAME                  VARCHAR(50)   NOT NULL,
  SURNAME               VARCHAR(50)   NOT NULL,
  ACTIVE                BOOLEAN       NOT NULL      DEFAULT TRUE,
  CREATED_BY            BIGSERIAL     REFERENCES    CRM.USER(id),
  CREATED               TIMESTAMP,
  MODIFIED              TIMESTAMP,
  MODIFIED_BY           BIGSERIAL     REFERENCES    CRM.USER(id)
);;

CREATE UNIQUE INDEX CUSTOMER_NAME_SURNAME_UINDEX ON CRM.CUSTOMER (NAME, SURNAME);;
CREATE UNIQUE INDEX CUSTOMER_UUID_UINDEX ON CRM.CUSTOMER (UUID);;

CREATE TRIGGER CUSTOMER_UUID_TRIGGER
  BEFORE INSERT
  ON CRM.CUSTOMER
  FOR EACH ROW
EXECUTE PROCEDURE generate_uuid();;

CREATE TRIGGER CUSTOMER_CREATED_TRIGGER
  BEFORE INSERT
  ON CRM.CUSTOMER
  FOR EACH ROW
EXECUTE PROCEDURE update_created_timestamp();;

CREATE TRIGGER CUSTOMER_MODIFIED_TRIGGER
  BEFORE INSERT OR UPDATE
  ON CRM.CUSTOMER
  FOR EACH ROW
EXECUTE PROCEDURE update_modified_timestamp();;


# --- !Downs

DROP TABLE CRM.CUSTOMER;;