/*
 * This file is generated by jOOQ.
*/
package model.jooq;


import javax.annotation.Generated;

import model.jooq.tables.Customer;
import model.jooq.tables.Login;
import model.jooq.tables.Role;
import model.jooq.tables.User;


/**
 * Convenience access to all tables in crm
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>crm.customer</code>.
     */
    public static final Customer CUSTOMER = model.jooq.tables.Customer.CUSTOMER;

    /**
     * The table <code>crm.login</code>.
     */
    public static final Login LOGIN = model.jooq.tables.Login.LOGIN;

    /**
     * The table <code>crm.role</code>.
     */
    public static final Role ROLE = model.jooq.tables.Role.ROLE;

    /**
     * The table <code>crm.user</code>.
     */
    public static final User USER = model.jooq.tables.User.USER;
}
